import i18n from '../i18n';

export type LegalSection = {
  title: string;
  updated?: string;
  sections: string[];
};

export const getLegalText = (): Record<'terms' | 'privacy', LegalSection> => {
  const lang = i18n.language;

  if (lang === 'en') {
    return {
      terms: {
        title: 'Terms of Use',
        sections: [
          'Effective date: 13/01/2026',
          'By downloading, installing or using Asinu Lite, you agree to be bound by these Terms.',
          '1. Medical Disclaimer – MANDATORY',
          'ASINU LITE IS NOT A MEDICAL DEVICE, NOR SOFTWARE FOR DIAGNOSING, TREATING, OR PREVENTING DISEASE.',
          'Asinu Lite is only a tool for recording and tracking data you enter.',
          'All information/charts/statistics displayed are for reference and personal management purposes only.',
          'You must consult a doctor or qualified healthcare professional before making any decisions related to health, medication, or treatment.',
          'In case of emergency, contact the nearest medical facility.',
          '2. Responsibility for user-entered data',
          'You agree that the data you enter is accurate, complete, and up to date.',
          'You are responsible for any consequences arising from entering incorrect/incomplete data or using data inappropriately.',
          'Asinu Lite is not responsible if tracking results are inaccurate due to incorrect input data.',
          '3. Account and security',
          'You are responsible for keeping your login information confidential.',
          'If you detect unauthorized access, please notify us immediately for support.',
          '4. Ownership and usage limitations',
          'The application, interface, content, and trademarks are the property of DIABOT (except for third-party components used under license).',
          'You may not copy, modify, reverse-engineer, exploit, or use the application for unlawful purposes.',
          '5. Limitation of liability',
          'To the extent permitted by law:',
          'DIABOT is not liable for indirect/consequential damages arising from the use or inability to use the application, or from inaccurate data you enter.',
          'DIABOT is not liable for medical decisions based on the application instead of professional advice.',
          '6. Termination and account deletion',
          'You may stop using the application at any time. You have the right to request Delete Account per the Privacy Policy. Account deletion will erase/anonymize data according to our procedures and legal retention obligations (if any).',
          '7. Changes to terms',
          'We may update these Terms from time to time. The latest version will be published on our website. Your continued use after an update is considered acceptance of the new version.',
          '8. Contact',
          'DIABOT JOINT STOCK COMPANY',
          'Email: diabotaiagent@gmail.com',
          'Phone: 0898888917',
          'Address: 12A, Lane 1/16, Alley 1 Thuy Linh, Linh Nam Ward, Hanoi, Vietnam'
        ]
      },
      privacy: {
        title: 'Privacy Policy',
        updated: 'Effective date: 13/01/2026',
        sections: [
          'Application: Asinu Lite',
          'Operating entity / Data controller: DIABOT JOINT STOCK COMPANY',
          'Business registration number: 0111234998',
          'Address: 12A, Lane 1/16, Alley 1 Thuy Linh, Linh Nam Ward, Hanoi, Vietnam',
          'Support email: diabotaiagent@gmail.com',
          'Phone: 0898888917',
          'This policy describes how Asinu Lite collects, uses, stores, shares, and protects your personal data and health data. By using the application, you confirm that you have read, understood, and agreed to this policy.',
          '1. Data definitions and legal roles',
          'Personal data: information associated with or that helps identify an individual.',
          'Sensitive personal data: includes health data. (In Asinu Lite, health data you enter is considered sensitive data).',
          'DIABOT is the data controller for personal data processed within the Asinu Lite system; infrastructure partners (if any) only serve a technical support role under agreements and security requirements.',
          '2. Data we collect',
          'Asinu Lite collects data in 2 categories:',
          '(A) Health data entered by the user (sensitive):',
          'Blood Glucose',
          'Blood Pressure',
          'Weight',
          'Water Intake',
          '(B) Account/basic data for service operation (if you create an account):',
          'Login/account identification information (e.g., phone number/email based on your chosen registration method)',
          'Minimum technical data for operation and security (error logs, device information as necessary for troubleshooting)',
          'You may choose not to provide certain data, but some tracking/charting features may not function fully.',
          '3. Legal basis for data processing',
          'We process data based on:',
          'Your consent when you actively enter data and use tracking features.',
          'The need to provide services at your request (display charts, statistics, history).',
          'Security and system safety obligations to prevent fraud and technical errors.',
          'You have the right to withdraw consent at any time; withdrawal of consent may limit certain features.',
          '4. Purpose of data use',
          'Data is used to:',
          'Display personal health tracking charts and history',
          'Compile trend statistics over time (daily/weekly/monthly)',
          'Improve application quality and user support (fix bugs, optimize experience)',
          'Asinu Lite does not sell data and does not exploit health data to "monetize data".',
          '5. Sharing data with third parties',
          'Principles:',
          'No selling – no renting – no exchanging personal data/health data with third parties.',
          'Data is shared only in the following minimal cases:',
          'Technical infrastructure providers (hosting/cloud/email/error monitoring) when needed for service operation, and these parties must comply with security requirements under contract.',
          'Lawful requests from competent government authorities as required by law.',
          'Protecting the lawful rights and interests of DIABOT and users in case of disputes/fraud/violations.',
          '6. Storage and retention period (Data retention)',
          'Data is stored for as long as your account is active so you can review history and charts.',
          'When you request account deletion, we will delete or anonymize data as described in Section 8 below, except data required by law to be retained (if any) or necessary for dispute resolution.',
          'Some technical backups may exist for a limited time according to backup cycles, after which they will be automatically overwritten/deleted.',
          '7. Data security',
          'We apply reasonable technical and organizational safeguards, for example:',
          'Internal access control based on permissions',
          'Encryption/secure transmission channels (when transmitting data)',
          'Monitoring and logging technical incidents to improve system safety',
          'However, no system is absolutely secure. In the event of an unauthorized data breach, we will take steps in accordance with the law and notify as necessary.',
          '8. User rights (Data subject rights) & Delete Account',
          'You have the right to:',
          'View, edit, and update the data you have entered',
          'Request access to/a copy of your data (within system capabilities)',
          'Withdraw consent for data processing',
          'Request data deletion and account deletion (Delete Account)',
          'Delete Account – how to do it:',
          'In the application: go to Settings -> Account -> Delete Account and follow the instructions. (Required by Apple for apps with account creation).',
          'Or contact email: diabotaiagent@gmail.com with the subject "Request to delete Asinu account".',
          'After verifying account ownership, we will proceed to delete/anonymize data according to our internal process within a reasonable time.',
          '9. Children\'s data',
          'Asinu Lite is intended for adults. If you are a parent/guardian and allow a child to use it, you are responsible for consent and the data entered.',
          '10. International data transfers (if applicable)',
          'In cases where technical infrastructure is located outside Vietnam or cross-border processing occurs, we will comply with Vietnamese personal data protection laws and apply appropriate security measures.',
          '11. Contact',
          'If you have questions/complaints regarding privacy, please contact:',
          'DIABOT JOINT STOCK COMPANY – Email: diabotaiagent@gmail.com – Phone: 0898888917'
        ]
      }
    };
  }

  return {
    terms: {
      title: 'Điều khoản sử dụng',
      sections: [
        'Ngày hiệu lực: 13/01/2026',
        'Bằng việc tải xuống, cài đặt hoặc sử dụng Asinu Lite, bạn đồng ý bị ràng buộc bởi Điều khoản này.',
        '1. Medical Disclaimer (Miễn trừ trách nhiệm y tế) – BẮT BUỘC',
        'ASINU LITE KHÔNG PHẢI THIẾT BỊ Y TẾ, KHÔNG PHẢI PHẦN MỀM CHẨN ĐOÁN, ĐIỀU TRỊ, HOẶC PHÒNG NGỪA BỆNH.',
        'Asinu Lite chỉ là công cụ ghi chép và theo dõi dữ liệu do bạn nhập.',
        'Mọi thông tin/biểu đồ/thống kê hiển thị chỉ nhằm mục đích tham khảo và quản lý cá nhân.',
        'Bạn phải tham khảo bác sĩ hoặc chuyên gia y tế có chuyên môn trước mọi quyết định liên quan đến sức khỏe, thuốc, chế độ điều trị.',
        'Trong trường hợp khẩn cấp, hãy liên hệ cơ sở y tế gần nhất.',
        '2. Trách nhiệm dữ liệu do người dùng nhập',
        'Bạn cam kết dữ liệu bạn nhập là đúng, đầy đủ và cập nhật theo thực tế.',
        'Bạn chịu trách nhiệm đối với hậu quả phát sinh từ việc nhập sai/thiếu hoặc sử dụng dữ liệu theo cách không phù hợp.',
        'Asinu Lite không chịu trách nhiệm nếu kết quả theo dõi bị sai lệch do dữ liệu đầu vào không chính xác.',
        '3. Tài khoản và bảo mật',
        'Bạn chịu trách nhiệm giữ bí mật thông tin đăng nhập.',
        'Nếu phát hiện truy cập trái phép, bạn cần thông báo ngay cho chúng tôi để hỗ trợ.',
        '4. Quyền sở hữu và giới hạn sử dụng',
        'Ứng dụng, giao diện, nội dung, nhãn hiệu thuộc quyền sở hữu của DIABOT (trừ các thành phần thuộc bên thứ ba được cấp phép).',
        'Bạn không được sao chép, sửa đổi, đảo ngược mã, khai thác trái phép hoặc sử dụng ứng dụng vào mục đích vi phạm pháp luật.',
        '5. Giới hạn trách nhiệm',
        'Trong phạm vi pháp luật cho phép:',
        'DIABOT không chịu trách nhiệm cho thiệt hại gián tiếp/phát sinh do việc sử dụng hoặc không thể sử dụng ứng dụng, hoặc do dữ liệu bạn nhập không chính xác.',
        'DIABOT không chịu trách nhiệm cho quyết định y tế dựa trên ứng dụng thay vì tư vấn chuyên môn.',
        '6. Chấm dứt và xóa tài khoản',
        'Bạn có thể ngừng sử dụng ứng dụng bất cứ lúc nào. Bạn có quyền yêu cầu Delete Account theo Chính sách quyền riêng tư. Việc xóa tài khoản sẽ xóa/ẩn danh hóa dữ liệu theo quy trình và nghĩa vụ lưu trữ hợp pháp (nếu có).',
        '7. Thay đổi điều khoản',
        'Chúng tôi có thể cập nhật Điều khoản theo thời gian. Phiên bản mới nhất sẽ được công bố trên website. Việc bạn tiếp tục sử dụng sau khi cập nhật được hiểu là bạn đồng ý với phiên bản mới.',
        '8. Liên hệ',
        'CÔNG TY CỔ PHẦN DIABOT',
        'Email: diabotaiagent@gmail.com',
        'SĐT: 0898888917',
        'Địa chỉ: 12A, Ngách 1/16, Ngõ 1 Thúy Lĩnh, P. Lĩnh Nam, TP. Hà Nội, Việt Nam'
      ]
    },
    privacy: {
      title: 'Chính sách quyền riêng tư',
      updated: 'Ngày hiệu lực: 13/01/2026',
      sections: [
        'Ứng dụng: Asinu Lite',
        'Đơn vị vận hành/Chủ quản dữ liệu: CÔNG TY CỔ PHẦN DIABOT (DIABOT JOINT STOCK COMPANY)',
        'Mã số doanh nghiệp: 0111234998',
        'Địa chỉ: 12A, Ngách 1/16, Ngõ 1 Thúy Lĩnh, P. Lĩnh Nam, TP. Hà Nội, Việt Nam',
        'Email hỗ trợ: diabotaiagent@gmail.com',
        'SĐT: 0898888917',
        'Chính sách này mô tả cách Asinu Lite thu thập, sử dụng, lưu trữ, chia sẻ và bảo vệ dữ liệu cá nhân và dữ liệu sức khỏe của bạn. Khi sử dụng ứng dụng, bạn xác nhận đã đọc, hiểu và đồng ý với nội dung chính sách này.',
        '1. Định nghĩa dữ liệu và vai trò pháp lý',
        'Dữ liệu cá nhân: thông tin gắn với hoặc giúp nhận diện một cá nhân.',
        'Dữ liệu cá nhân nhạy cảm: bao gồm dữ liệu về sức khỏe. (Trong Asinu Lite, dữ liệu sức khỏe do bạn nhập là dữ liệu nhạy cảm).',
        'DIABOT là Bên kiểm soát dữ liệu cá nhân (data controller) đối với dữ liệu được xử lý trong hệ thống Asinu Lite; các đối tác hạ tầng (nếu có) chỉ đóng vai trò hỗ trợ kỹ thuật theo thỏa thuận và yêu cầu bảo mật.',
        '2. Dữ liệu chúng tôi thu thập',
        'Asinu Lite thu thập dữ liệu theo 2 nhóm:',
        '(A) Dữ liệu sức khỏe do người dùng tự nhập (nhạy cảm):',
        'Đường huyết (Blood Glucose)',
        'Huyết áp (Blood Pressure)',
        'Cân nặng (Weight)',
        'Lượng nước uống (Water Intake)',
        '(B) Dữ liệu tài khoản/cơ bản để vận hành dịch vụ (nếu bạn tạo tài khoản):',
        'Thông tin đăng nhập/định danh tài khoản (ví dụ: số điện thoại/email theo cơ chế đăng ký bạn lựa chọn)',
        'Dữ liệu kỹ thuật tối thiểu phục vụ vận hành và bảo mật (nhật ký lỗi, thông tin thiết bị ở mức cần thiết để khắc phục sự cố)',
        'Bạn có thể lựa chọn không cung cấp một số dữ liệu, nhưng khi đó một số tính năng theo dõi/biểu đồ có thể không hoạt động đầy đủ.',
        '3. Căn cứ xử lý dữ liệu (Legal basis)',
        'Chúng tôi xử lý dữ liệu dựa trên:',
        'Sự đồng ý của bạn khi bạn chủ động nhập dữ liệu và sử dụng các tính năng theo dõi.',
        'Nhu cầu cung cấp dịch vụ theo yêu cầu của bạn (hiển thị biểu đồ, thống kê, lịch sử).',
        'Nghĩa vụ bảo mật và an toàn hệ thống để phòng chống gian lận, lỗi kỹ thuật.',
        'Bạn có quyền rút lại sự đồng ý bất cứ lúc nào; việc rút lại đồng ý có thể làm hạn chế một số chức năng.',
        '4. Mục đích sử dụng dữ liệu',
        'Dữ liệu được sử dụng để:',
        'Hiển thị biểu đồ và lịch sử theo dõi sức khỏe cá nhân',
        'Thống kê xu hướng theo thời gian (ngày/tuần/tháng)',
        'Cải thiện chất lượng ứng dụng và hỗ trợ người dùng (khắc phục lỗi, tối ưu trải nghiệm)',
        'Asinu Lite không bán dữ liệu và không khai thác dữ liệu sức khỏe để "kiếm tiền từ dữ liệu".',
        '5. Chia sẻ dữ liệu với bên thứ ba',
        'Nguyên tắc:',
        'Không bán – không cho thuê – không trao đổi dữ liệu cá nhân/dữ liệu sức khỏe cho bên thứ ba.',
        'Chỉ chia sẻ dữ liệu trong các trường hợp tối thiểu sau:',
        'Nhà cung cấp hạ tầng kỹ thuật (lưu trữ/đám mây/email/giám sát lỗi) khi cần để vận hành dịch vụ, và các bên này phải tuân thủ yêu cầu bảo mật theo hợp đồng.',
        'Yêu cầu hợp pháp của cơ quan nhà nước có thẩm quyền theo quy định pháp luật.',
        'Bảo vệ quyền và lợi ích hợp pháp của DIABOT và người dùng trong trường hợp có tranh chấp/gian lận/vi phạm.',
        '6. Lưu trữ và thời hạn lưu trữ (Data retention)',
        'Dữ liệu được lưu trong suốt thời gian tài khoản của bạn còn hoạt động để bạn xem lại lịch sử và biểu đồ.',
        'Khi bạn yêu cầu xóa tài khoản, chúng tôi sẽ xóa hoặc ẩn danh hóa dữ liệu theo Mục 8 dưới đây, trừ phần dữ liệu mà pháp luật yêu cầu phải lưu (nếu có) hoặc cần thiết để giải quyết tranh chấp.',
        'Một số bản sao lưu kỹ thuật (backup) có thể tồn tại trong thời gian giới hạn theo chu kỳ sao lưu, sau đó sẽ tự động bị ghi đè/xóa.',
        '7. Bảo mật dữ liệu',
        'Chúng tôi áp dụng biện pháp bảo vệ hợp lý về kỹ thuật và tổ chức, ví dụ:',
        'Kiểm soát truy cập nội bộ theo phân quyền',
        'Mã hóa/kênh truyền an toàn (khi truyền dữ liệu)',
        'Giám sát và ghi nhận sự cố kỹ thuật để tăng an toàn hệ thống',
        'Tuy nhiên, không hệ thống nào an toàn tuyệt đối. Trong trường hợp xảy ra sự cố rò rỉ trái phép, chúng tôi sẽ thực hiện các bước xử lý theo quy định pháp luật và thông báo khi cần thiết.',
        '8. Quyền của người dùng (Data subject rights) & Delete Account',
        'Bạn có quyền:',
        'Xem, chỉnh sửa, cập nhật dữ liệu bạn đã nhập',
        'Yêu cầu truy cập/bản sao dữ liệu (trong phạm vi hệ thống cho phép)',
        'Rút lại đồng ý xử lý dữ liệu',
        'Yêu cầu xóa dữ liệu và xóa tài khoản (Delete Account)',
        'Delete Account – cách thực hiện:',
        'Trong ứng dụng: vào Cài đặt → Tài khoản → Xóa tài khoản và làm theo hướng dẫn. (Yêu cầu bắt buộc của Apple với app có tạo tài khoản).',
        'Hoặc liên hệ email: diabotaiagent@gmail.com với tiêu đề "Yêu cầu xóa tài khoản Asinu".',
        'Sau khi xác minh đúng chủ tài khoản, chúng tôi sẽ tiến hành xóa/ẩn danh hóa dữ liệu theo quy trình nội bộ trong thời gian hợp lý.',
        '9. Dữ liệu trẻ em',
        'Asinu Lite hướng đến người trưởng thành. Nếu bạn là cha/mẹ/người giám hộ và cho phép trẻ em sử dụng, bạn chịu trách nhiệm về sự đồng ý và dữ liệu được nhập.',
        '10. Chuyển dữ liệu ra nước ngoài (nếu có)',
        'Trong trường hợp hạ tầng kỹ thuật đặt ngoài Việt Nam hoặc có xử lý xuyên biên giới, chúng tôi sẽ thực hiện theo quy định pháp luật Việt Nam về bảo vệ dữ liệu cá nhân và áp dụng biện pháp bảo mật phù hợp.',
        '11. Liên hệ',
        'Nếu có câu hỏi/khiếu nại liên quan quyền riêng tư, vui lòng liên hệ:',
        'DIABOT JOINT STOCK COMPANY – Email: diabotaiagent@gmail.com – SĐT: 0898888917'
      ]
    }
  };
};

/** @deprecated Use getLegalText() instead for language-reactive content */
export const LEGAL_TEXT = getLegalText();
