import i18n from '../i18n';

export type LegalSection = {
  title: string;
  updated?: string;
  sections: string[];
};

type LegalContent = Record<'terms' | 'privacy' | 'dataDeletion', LegalSection>;

const vi: LegalContent = {
  terms: {
    title: 'Điều Khoản Sử Dụng Dịch Vụ',
    updated: 'Cập nhật lần cuối: Ngày 22 tháng 05 năm 2026',
    sections: [
      'Chào mừng bạn đến với Hệ sinh thái Chăm sóc Sức khỏe Asinu (sau đây gọi tắt là “Asinu” hoặc “Chúng tôi”).',
      'Vui lòng đọc kỹ tài liệu Điều khoản Sử dụng Dịch vụ này trước khi bắt đầu sử dụng các tính năng trên ứng dụng di động Asinu hoặc trang web liên kết. Bằng cách đăng ký tài khoản, tải ứng dụng hoặc sử dụng bất kỳ phần nào của Dịch vụ, bạn đã đồng ý chịu sự ràng buộc pháp lý bởi các Điều khoản này, bao gồm cả Chính sách Bảo mật Thông tin Cá nhân của chúng tôi. Nếu bạn không đồng ý với bất kỳ điều khoản nào dưới đây, vui lòng dừng sử dụng Dịch vụ ngay lập tức.',
      '1. TUYÊN BỐ MIỄN TRỪ TRÁCH NHIỆM Y TẾ (MEDICAL DISCLAIMER)',
      '1. Không phải là Cơ sở Y tế hay Thiết bị Chẩn đoán chuyên dụng:',
      '– Ứng dụng Asinu là một giải pháp công nghệ hỗ trợ kết nối gia đình, bác sĩ và ghi nhận, hiển thị các chỉ số sinh hiệu đo lường từ thiết bị ngoại vi của bạn (như đồng hồ thông minh, máy đo huyết áp kết nối Bluetooth).',
      '– Asinu KHÔNG PHẢI LÀ MỘT CƠ SỞ Y TẾ, không cung cấp dịch vụ khám chữa bệnh khẩn cấp, và các nội dung hiển thị trong ứng dụng (bao gồm biểu đồ, cảnh báo sức khỏe tự động, gợi ý thói quen) KHÔNG THỂ THAY THẾ cho các chẩn đoán chuyên môn, đơn thuốc, lời khuyên chuyên khoa, hoặc phác đồ điều trị của bác sĩ được cấp phép.',
      '2. Không phụ thuộc tuyệt đối vào hệ thống trong các tình huống khẩn cấp:',
      '– Các cảnh báo sinh hiệu tự động trên ứng dụng (như cảnh báo nhịp tim cao, huyết áp bất thường) phụ thuộc hoàn toàn vào độ chính xác của thiết bị đo lường cá nhân của bạn, kết nối Bluetooth, sóng viễn thông và kết nối Internet của thiết bị di động. Chúng tôi không đảm bảo các cảnh báo này sẽ luôn được gửi đi đúng lúc 100% trong mọi điều kiện kỹ thuật.',
      '– TÌNH HUỐNG KHẨN CẤP: Khi người dùng (đặc biệt là người cao tuổi) xảy ra các dấu hiệu suy giảm sức khỏe đột ngột hoặc tình huống nguy kịch liên quan đến tính mạng, người dùng hoặc người thân của người dùng PHẢI NGAY LẬP TỨC liên hệ với Trung tâm cấp cứu 115 hoặc di chuyển khẩn cấp đến cơ sở y tế gần nhất. Tuyệt đối không được chờ đợi phản hồi từ ứng dụng Asinu hoặc trì hoãn việc cấp cứu do dựa vào các chỉ số hiển thị trên ứng dụng.',
      '3. Miễn trừ trách nhiệm pháp lý về sức khỏe:',
      '– Asinu từ chối mọi trách nhiệm pháp lý đối với bất kỳ hậu quả nào liên quan đến sức khỏe, chấn thương, biến chứng hoặc tử vong của người dùng phát sinh từ việc:',
      '– Thiết bị đo lường ngoại vi của người dùng báo sai lệch chỉ số.',
      '– Đường truyền Internet, lỗi mạng viễn thông hoặc lỗi hệ thống làm chậm trễ việc gửi thông báo cảnh báo SOS khẩn cấp đến người thân.',
      '– Người dùng hoặc người thân tự ý điều chỉnh đơn thuốc, phương pháp điều trị mà không có sự chỉ định trực tiếp từ bác sĩ chuyên khoa dựa trên các dữ liệu tham khảo từ ứng dụng.',
      '– Các tư vấn của bác sĩ liên kết trên nền tảng (các bác sĩ tư vấn tự chịu trách nhiệm chuyên môn nghề nghiệp đối với các chẩn đoán từ xa của họ theo quy định của pháp luật y tế).',
      '2. QUY ĐỊNH VỀ ĐĂNG KÝ TÀI KHOẢN VÀ BẢO MẬT',
      '1. Điều kiện sử dụng: Người sử dụng ứng dụng để đăng ký tài khoản theo dõi sức khỏe trực tiếp phải từ đủ 18 tuổi trở lên hoặc có sự đồng ý, giám sát trực tiếp từ người giám hộ hợp pháp (đối với người cao tuổi không tự chủ hành vi công nghệ hoặc người dưới 18 tuổi).',
      '2. Thông tin đăng ký: Bạn cam kết cung cấp số điện thoại chính chủ và các thông tin cá nhân chính xác khi đăng ký tài khoản. Bạn hoàn toàn chịu trách nhiệm trước pháp luật về tính chính xác của các thông tin này.',
      '3. Bảo mật tài khoản: Bạn chịu trách nhiệm tự bảo mật mật khẩu và thiết bị đăng nhập ứng dụng của mình. Mọi hoạt động được thực hiện qua tài khoản của bạn được coi là do bạn thực hiện. Nếu phát hiện tài khoản bị xâm nhập trái phép, bạn phải thông báo ngay cho ban quản trị Asinu qua hotline/email hỗ trợ.',
      '3. CHÍNH SÁCH THANH TOÁN VÀ ĐIỂM THƯỞNG LOYALTY POINTS (HOẶC VIRTUAL CURRENCY)',
      '1. Gói Dịch vụ trả phí: Asinu cung cấp cả gói dịch vụ miễn phí và các gói dịch vụ nâng cấp trả phí (như theo dõi chuyên sâu, gọi điện cảnh báo tự động qua cuộc gọi tổng đài, tư vấn bác sĩ riêng). Giá cước và điều kiện của các gói dịch vụ này được hiển thị rõ ràng trên ứng dụng. Mọi thanh toán đều tuân thủ chính sách giao dịch của bên thứ ba (Apple IAP, Google Billing, hoặc Cổng thanh toán tại Việt Nam).',
      '2. Cơ chế Điểm thưởng Loyalty Points (Voucher):',
      '– Người dùng có thể tích lũy Điểm thưởng Loyalty thông qua các hoạt động rèn luyện sức khỏe (như đi đủ số bước chân hàng ngày), hoàn thành nhiệm vụ theo dõi sức khỏe hoặc mua các gói nâng cấp dịch vụ.',
      '– QUY ĐỊNH BẮT BUỘC: Điểm thưởng Loyalty Points KHÔNG CÓ GIÁ TRỊ QUY ĐỔI TRỰC TIẾP THÀNH TIỀN MẶT, VÀNG HOẶC CÁC CÔNG CỤ THANH TOÁN CÓ GIÁ TRỊ TƯƠNG ĐƯƠNG bên ngoài ứng dụng. Điểm thưởng chỉ được dùng để:',
      '– Nâng cấp các tính năng VIP trong ứng dụng Asinu.',
      '– Đổi thành các Voucher giảm giá dịch vụ khám chữa bệnh tại các phòng khám, bệnh viện đối tác liên kết của Asinu.',
      '– Mọi hành vi mua bán, đầu cơ, chuyển nhượng điểm thưởng giữa các tài khoản trái phép nhằm mục đích trục lợi tài chính đều bị cấm và sẽ bị khóa tài khoản vĩnh viễn không cần báo trước.',
      '4. QUYỀN SỞ HỮU TRÍ TUỆ',
      'Toàn bộ quyền sở hữu trí tuệ liên quan đến Hệ sinh thái Asinu bao gồm: mã nguồn (source code), thiết kế giao diện (UI/UX), logo, nhãn hiệu thương mại “Asinu”, các hình ảnh đồ họa, bài viết chuyên môn và toàn bộ tài liệu đi kèm đều thuộc quyền sở hữu độc quyền của ban quản trị Asinu (hoặc sếp Trần Quang Tùng / đơn vị chủ quản hợp pháp).',
      'Bạn không được phép sao chép, sửa đổi, phân phối, giải mã mã nguồn (reverse engineer), hoặc sử dụng các tài sản trí tuệ này cho bất kỳ mục đích thương mại nào khác mà không có sự đồng ý bằng văn bản từ chúng tôi.',
      '5. CÁC HÀNH VI BỊ CẤM KHI SỬ DỤNG DỊCH VỤ',
      'Người dùng tuyệt đối không được thực hiện các hành vi sau đây:',
      '1. Sử dụng ứng dụng vào các mục đích vi phạm pháp luật Việt Nam.',
      '2. Cố tình gửi các cảnh báo giả mạo, spam nút bấm SOS khẩn cấp làm gián đoạn hệ thống hỗ trợ và gây hoang mang cho người thân hoặc bác sĩ.',
      '3. Sử dụng thông tin giả mạo để đăng ký tài khoản, hoặc giả danh bác sĩ, chuyên gia y tế trên nền tảng nhằm trục lợi.',
      '4. Tấn công, phát tán mã độc, virus, hoặc cố tình dò quét lỗ hổng bảo mật của ứng dụng và máy chủ VPS của Asinu.',
      '5. Đăng tải hoặc gửi đi các nội dung thô tục, bôi nhọ danh dự của người khác hoặc các thông tin trái với thuần phong mỹ tục Việt Nam trong phần trò chuyện kết nối.',
      '6. GIỚI HẠN TRÁCH NHIỆM PHÁP LÝ TỐI ĐA',
      'Trong phạm vi tối đa được luật pháp Việt Nam cho phép:',
      '1. Chúng tôi cung cấp Dịch vụ trên cơ sở “nguyên trạng” (as-is) và không đưa ra bất kỳ bảo đảm nào về tính liên tục tuyệt đối, không có lỗi kỹ thuật của ứng dụng trong quá trình vận hành.',
      '2. Trong mọi trường hợp, tổng trách nhiệm bồi thường thiệt hại của Asinu đối với bất kỳ khiếu nại nào phát sinh từ hoặc liên quan đến việc sử dụng Dịch vụ sẽ không vượt quá tổng số tiền thực tế bạn đã thanh toán cho các gói dịch vụ trả phí của Asinu trong vòng mười hai (12) tháng gần nhất tính đến thời điểm phát sinh tranh chấp.',
      '7. ĐÌNH CHỈ VÀ CHẤM DỨT DỊCH VỤ',
      '1. Do người dùng chủ động: Bạn có thể ngừng sử dụng dịch vụ và yêu cầu xóa tài khoản của mình bất cứ lúc nào theo quy trình tại `/data-deletion`.',
      '2. Do Asinu chủ động: Chúng tôi có quyền tạm ngừng hoặc chấm dứt vĩnh viễn quyền truy cập Dịch vụ của bạn mà không phải chịu bất kỳ trách nhiệm pháp lý nào nếu:',
      '– Bạn vi phạm nghiêm trọng bất kỳ điều khoản nào quy định tại đây.',
      '– Dịch vụ bị chấm dứt hoạt động hoàn toàn do quyết định chiến lược của Ban quản trị hoặc do thay đổi về luật pháp quản lý dịch vụ y tế công nghệ của Nhà nước.',
      '8. LUẬT ÁP DỤNG VÀ GIẢI QUYẾT TRANH CHẤP',
      '1. Luật áp dụng: Điều khoản này được điều chỉnh và giải thích theo các quy định của pháp luật nước Cộng hòa Xã hội Chủ nghĩa Việt Nam.',
      '2. Giải quyết tranh chấp: Mọi tranh chấp phát sinh từ hoặc liên quan đến việc sử dụng Dịch vụ trước tiên sẽ được giải quyết thông qua thương lượng, hòa giải thiện chí giữa hai bên. Trong trường hợp không thể giải quyết bằng thương lượng trong vòng 30 ngày, tranh chấp sẽ được đưa ra giải quyết tại Tòa án nhân dân có thẩm quyền tại Thành phố Hà Nội (hoặc nơi đặt trụ sở chính của đơn vị chủ quản Dịch vụ) để xét xử chung thẩm theo đúng quy định pháp luật.',
      'Mọi đóng góp ý kiến hoặc phản hồi về điều khoản sử dụng, xin đại ca và các bạn vui lòng gửi về hòm thư hỗ trợ của chúng tôi tại info@asinu.vn.'
    ]
  },
  privacy: {
    title: 'Chính Sách Bảo Mật Thông Tin Cá Nhân',
    updated: 'Cập nhật lần cuối: Ngày 22 tháng 05 năm 2026',
    sections: [
      'Chào mừng bạn đến với Hệ sinh thái Chăm sóc Sức khỏe Asinu (bao gồm Ứng dụng di động Asinu trên iOS/Android và Website asinu.vn / asinu.top, sau đây gọi chung là “Dịch vụ” hoặc “Chúng tôi”).',
      'Chúng tôi cam kết tôn trọng quyền riêng tư và bảo vệ an toàn thông tin cá nhân của bạn. Chính sách Bảo mật này được xây dựng tuân thủ nghiêm ngặt theo Nghị định số 13/2023/NĐ-CP của Chính phủ Việt Nam về Bảo vệ dữ liệu cá nhân, Luật An toàn thông tin mạng năm 2015, cũng như các tiêu chuẩn bảo vệ dữ liệu toàn cầu của Apple App Store và Google Play Store.',
      'Chính sách này giải thích cách chúng tôi thu thập, sử dụng, lưu trữ, xử lý, chia sẻ và bảo vệ dữ liệu cá nhân của bạn khi bạn sử dụng Dịch vụ của chúng tôi. Xin vui lòng đọc kỹ trước khi đăng ký hoặc sử dụng dịch vụ. Khi bạn nhấn nút “Đồng ý” hoặc tiếp tục sử dụng ứng dụng, bạn được coi là đã đọc, hiểu và tự nguyện đồng ý với toàn bộ nội dung của Chính sách này.',
      '1. PHÂN LOẠI DỮ LIỆU CÁ NHÂN CHÚNG TÔI THU THẬP',
      'Nhằm cung cấp các tính năng theo dõi sức khỏe và kết nối gia đình hiệu quả, Chúng tôi cần thu thập các nhóm dữ liệu cá nhân sau đây:',
      'A. Dữ liệu cá nhân cơ bản',
      '1. Thông tin định danh cá nhân: Họ và tên, Ngày tháng năm sinh, Giới tính, Ảnh đại diện.',
      '2. Thông tin liên hệ: Số điện thoại (dùng làm tài khoản đăng nhập chính và nhận thông báo khẩn cấp), Địa chỉ email, Địa chỉ nơi cư trú (phục vụ mục đích hỗ trợ khẩn cấp hoặc gửi thiết bị y tế).',
      '3. Mối quan hệ gia đình: Thông tin kết nối giữa tài khoản người cao tuổi (người cần chăm sóc) và tài khoản người thân/người giám hộ (người theo dõi).',
      '4. Thông tin tài chính: Lịch sử giao dịch, hóa đơn thanh toán khi bạn nâng cấp gói dịch vụ hoặc mua các dịch vụ y tế liên kết (Chúng tôi không lưu giữ thông tin chi tiết thẻ tín dụng hoặc tài khoản ngân hàng của bạn; mọi giao dịch thanh toán đều được thực hiện an toàn qua các cổng thanh toán được cấp phép).',
      'B. Dữ liệu cá nhân nhạy cảm (Dữ liệu Sức khỏe)',
      'Theo quy định của pháp luật Việt Nam, thông tin về sức khỏe cá nhân là dữ liệu cá nhân nhạy cảm, đòi hỏi các biện pháp bảo vệ đặc biệt. Chúng tôi thu thập:',
      '1. Các chỉ số sinh hiệu đo lường trực tiếp: Huyết áp, Nhịp tim, Nồng độ oxy trong máu (SpO2), Đường huyết, Chỉ số khối cơ thể (BMI), Chiều cao, Cân nặng.',
      '2. Thông tin y tế bổ sung: Tiền sử bệnh lý, Dị ứng thuốc, Ghi chú sức khỏe hàng ngày do bạn hoặc người thân của bạn tự cập nhật.',
      '3. Dữ liệu tư vấn y tế: Các ghi chú tư vấn, đề xuất y khoa của các bác sĩ, chuyên gia chăm sóc sức khỏe có liên kết với hệ thống khi bạn chủ động kết nối dịch vụ với họ.',
      '4. Dữ liệu định vị vị trí: Vị trí địa lý GPS của thiết bị sử dụng (chỉ được thu thập khi bạn kích hoạt tính năng “Gửi cảnh báo SOS khẩn cấp” để giúp người thân hoặc nhân viên y tế xác định chính xác vị trí của người cao tuổi trong tình huống nguy hiểm).',
      'C. Dữ liệu kỹ thuật thu thập tự động',
      '1. Thông tin thiết bị: Địa chỉ IP, loại thiết bị di động, hệ điều hành thiết bị, định danh duy nhất của thiết bị (UUID), ngôn ngữ sử dụng.',
      '2. Dữ liệu hoạt động (Log data): Thời gian sử dụng ứng dụng, các tính năng bạn đã tương tác, lịch sử lỗi hệ thống (crash dumps) để phục vụ công tác sửa lỗi và nâng cấp hiệu năng.',
      '2. MỤC ĐÍCH VÀ CƠ SỞ PHÁP LÝ XỬ LÝ DỮ LIỆU',
      'Chúng tôi xử lý dữ liệu cá nhân của bạn hoàn toàn dựa trên các cơ sở pháp lý vững chắc bao gồm: Sự đồng ý rõ ràng và tự nguyện của bạn (Consent) và Thực hiện hợp đồng cung cấp dịch vụ. Mục đích xử lý cụ thể như sau:',
      '1. Vận hành Dịch vụ: Thiết lập tài khoản, lưu trữ lịch sử chỉ số sức khỏe cá nhân theo thời gian thực để biểu diễn dưới dạng biểu đồ giúp bạn dễ dàng theo dõi.',
      '2. Kết nối Gia đình và Người thân: Chia sẻ tự động các chỉ số sức khỏe của bạn đến tài khoản của người thân hoặc người giám hộ do bạn chỉ định và cấp quyền trong ứng dụng.',
      '3. Cảnh báo Khẩn cấp tự động: Phát hiện các chỉ số sức khỏe vượt ngưỡng an toàn (ví dụ: huyết áp tăng quá cao, nhịp tim bất thường) để gửi cảnh báo tức thời qua thông báo đẩy (push), tin nhắn SMS hoặc cuộc gọi tự động đến người liên hệ khẩn cấp của bạn.',
      '4. Hỗ trợ Kết nối Y tế chuyên nghiệp: Cung cấp dữ liệu chỉ số sức khỏe cho các bác sĩ/chuyên gia y tế được bạn ủy quyền để hỗ trợ quá trình tư vấn chăm sóc sức khỏe trực tuyến.',
      '5. Cải tiến và Phát triển thuật toán: Phân tích dữ liệu ẩn danh (anonymized data) nhằm cải thiện thuật toán dự báo rủi ro sức khỏe sớm và nâng cao trải nghiệm người dùng trên ứng dụng.',
      '6. Bảo mật và Phòng ngừa gian lận: Xác thực danh tính người dùng, phát hiện và ngăn chặn các hành vi xâm nhập trái phép, phá hoại hệ thống.',
      '3. CƠ CHẾ ĐỒNG Ý VÀ RÚT LẠI SỰ ĐỒNG Ý (CONSENT MANAGEMENT)',
      '1. Đồng ý rõ ràng (Active Opt-in): Khi cài đặt ứng dụng lần đầu, bạn sẽ được yêu cầu đọc kịch bản này và tích chọn vào ô “Tôi đồng ý với Chính sách Bảo mật và cho phép thu thập dữ liệu sức khỏe cá nhân”. Đây là điều kiện bắt buộc để sử dụng dịch vụ do tính chất của ứng dụng là theo dõi sức khỏe.',
      '2. Rút lại sự đồng ý: Bạn có quyền rút lại sự đồng ý đối với việc xử lý dữ liệu cá nhân của mình vào bất kỳ lúc nào bằng cách:',
      '– Tắt quyền truy cập dữ liệu (Bluetooth, Vị trí, Thông báo) trong phần Cài đặt thiết bị di động của bạn.',
      '– Gửi yêu cầu rút lại sự đồng ý qua email hỗ trợ của chúng tôi.',
      '– Yêu cầu xóa tài khoản vĩnh viễn (lúc này toàn bộ dữ liệu sẽ ngừng xử lý và được xóa theo quy trình tại Mục 7).',
      'Lưu ý: Việc rút lại sự đồng ý không ảnh hưởng đến tính hợp pháp của việc xử lý dữ liệu trước khi bạn rút lại.',
      '4. CHIA SẺ VÀ TIẾT LỘ DỮ LIỆU CÁ NHÂN',
      'Chúng tôi cam kết TUYỆT ĐỐI KHÔNG BÁN, CHO THUÊ HOẶC TRAO ĐỔI dữ liệu cá nhân của bạn cho bất kỳ bên thứ ba nào vì mục đích thương mại hoặc quảng cáo. Dữ liệu của bạn chỉ được chia sẻ trong các trường hợp giới hạn sau đây:',
      '1. Người thân và Người giám hộ do bạn chỉ định: Hệ thống chỉ gửi dữ liệu sức khỏe của bạn đến đúng các tài khoản người thân mà bạn đã trực tiếp thao tác kết nối và cấp quyền trên app. Bạn có toàn quyền ngắt kết nối này bất cứ lúc nào.',
      '2. Bác sĩ và Cơ sở Y tế được ủy quyền: Khi bạn tham gia chương trình tư vấn sức khỏe từ xa trên Asinu, thông tin sức khỏe của bạn sẽ được chia sẻ cho bác sĩ do bạn chọn để thực hiện nhiệm vụ chuyên môn.',
      '3. Các đối tác xử lý dữ liệu kỹ thuật: Chúng tôi hợp tác với các nhà cung cấp dịch vụ uy tín (như dịch vụ lưu trữ đám mây AWS/Google Cloud, dịch vụ hạ tầng mạng Coolify/Nginx, hệ thống gửi SMS tự động Twilio/n8n). Các đối tác này chỉ được phép tiếp cận dữ liệu trong phạm vi tối thiểu để duy trì hoạt động kỹ thuật của hệ thống và chịu sự ràng buộc bởi các hợp đồng bảo mật nghiêm ngặt tương đương chính sách này.',
      '4. Yêu cầu pháp lý: Chúng tôi sẽ cung cấp dữ liệu cá nhân của bạn cho cơ quan quản lý nhà nước hoặc cơ quan thực thi pháp luật của Việt Nam khi có văn bản yêu cầu chính thức tuân theo đúng trình tự pháp luật quy định.',
      '5. BIỆN PHÁP BẢO MẬT VÀ LƯU TRỮ DỮ LIỆU NHẠY CẢM',
      'Đối với dữ liệu sức khỏe (dữ liệu nhạy cảm), Chúng tôi áp dụng các tiêu chuẩn bảo mật kỹ thuật cấp cao nhất bao gồm:',
      '1. Mã hóa dữ liệu truyền tải (In-Transit): Toàn bộ dữ liệu truyền đi giữa ứng dụng di động của bạn và hệ thống máy chủ được mã hóa bằng giao thức HTTPS/TLS với thuật toán mã hóa mạnh nhất.',
      '2. Mã hóa dữ liệu lưu trữ (At-Rest): Dữ liệu sức khỏe và thông tin định danh lưu trữ trong Cơ sở dữ liệu SQL/PostgreSQL trên VPS của chúng tôi đều được mã hóa bằng cơ chế mã hóa AES-256. Khóa giải mã được lưu trữ độc lập tại hệ thống quản lý khóa an toàn.',
      '3. Kiểm soát truy cập (Access Control): Nhân viên kỹ thuật của Asinu không có quyền xem trực tiếp dữ liệu thô chưa mã hóa của bạn. Việc truy cập database phục vụ mục đích bảo trì chỉ được cấp phép tạm thời cho Trưởng phòng Kỹ thuật (P2) khi được phê duyệt và được ghi nhật ký hệ thống (Audit Log) không thể chỉnh sửa.',
      '4. Sao lưu an toàn: Dữ liệu được sao lưu (backup) tự động hàng ngày và lưu trữ dưới dạng mã hóa trên máy chủ backup riêng biệt để đề phòng sự cố phần cứng.',
      '6. QUYỀN VÀ NGHĨA VỤ CỦA BẠN (CHỦ THỂ DỮ LIỆU)',
      'A. Quyền của bạn theo Nghị định 13/2023/NĐ-CP:',
      '1. Quyền được biết: Được biết về hoạt động xử lý dữ liệu cá nhân của mình.',
      '2. Quyền đồng ý hoặc không đồng ý: Quyền đồng ý hoặc từ chối cho phép xử lý dữ liệu.',
      '3. Quyền truy cập và chỉnh sửa: Bạn có thể tự truy cập vào trang cá nhân trong app để xem và chỉnh sửa thông tin cá nhân cơ bản của mình bất cứ lúc nào.',
      '4. Quyền rút lại sự đồng ý và Quyền xóa dữ liệu: Yêu cầu chúng tôi xóa vĩnh viễn toàn bộ thông tin cá nhân của bạn trên hệ thống.',
      '5. Quyền hạn chế hoặc phản đối xử lý dữ liệu: Quyền yêu cầu chúng tôi ngừng chia sẻ thông tin cho người thân hoặc bác sĩ nhưng vẫn giữ lại tài khoản.',
      '6. Quyền khiếu nại, tố cáo và yêu cầu bồi thường thiệt hại: Theo quy định của pháp luật nếu phát hiện chúng tôi vi phạm cam kết bảo mật.',
      'B. Nghĩa vụ của bạn:',
      '1. Cung cấp thông tin cá nhân và số điện thoại chính xác, chính chủ.',
      '2. Tự bảo mật thông tin đăng nhập tài khoản của mình. Không chia sẻ mật khẩu hoặc thiết bị cho người khác để tránh rò rỉ dữ liệu cá nhân ngoài ý muốn.',
      '3. Thông báo ngay cho chúng tôi nếu phát hiện bất kỳ hành vi xâm nhập trái phép nào vào tài khoản của bạn.',
      '7. QUY TRÌNH YÊU CẦU XÓA DỮ LIỆU (DATA DELETION)',
      'Nếu bạn không còn nhu cầu sử dụng dịch vụ của Asinu, bạn có thể thực hiện yêu cầu xóa tài khoản và dữ liệu cá nhân của mình theo hai cách:',
      '1. Thực hiện trong Ứng dụng (App): Vào mục Cài đặt tài khoản -> Chọn Xóa tài khoản vĩnh viễn. Hệ thống sẽ tự động gửi yêu cầu lên máy chủ.',
      '2. Thực hiện trực tuyến (Website): Truy cập đường dẫn asinu.vn/data-deletion và điền thông tin vào Form yêu cầu xóa mà không cần đăng nhập app.',
      'Quy trình xử lý của chúng tôi:',
      'Sau khi tiếp nhận yêu cầu, Chúng tôi sẽ tiến hành xác thực danh tính chủ sở hữu tài khoản qua mã OTP gửi về số điện thoại đăng ký.',
      'Trong vòng tối đa 72 giờ làm việc kể từ khi xác thực thành công, toàn bộ dữ liệu định danh, thông tin gia đình và lịch sử chỉ số sức khỏe của bạn trên cơ sở dữ liệu chính sẽ bị xóa vĩnh viễn (hoặc ẩn danh hóa hoàn toàn để không còn khả năng liên kết với danh tính của bạn).',
      'Một số dữ liệu tối thiểu liên quan đến hóa đơn thanh toán hoặc nghĩa vụ tài chính sẽ được lưu trữ cách ly dưới dạng ngoại lệ theo đúng thời hạn quy định của Luật Kế toán Việt Nam, và tuyệt đối không được sử dụng cho bất kỳ mục đích nào khác.',
      '8. THÔNG TIN LIÊN HỆ ĐƠN VỊ KIỂM SOÁT VÀ XỬ LÝ DỮ LIỆU',
      'Mọi câu hỏi, thắc mắc hoặc yêu cầu thực thi các quyền bảo vệ dữ liệu cá nhân của bạn, xin vui lòng liên hệ Bộ phận Bảo vệ Dữ liệu thuộc Ban quản trị dự án Asinu:',
      'Đơn vị chủ quản: Hệ sinh thái Chăm sóc Sức khỏe Asinu',
      'Người chịu trách nhiệm bảo vệ dữ liệu: Trưởng phòng Pháp Chế (P6) & Trưởng phòng Kỹ thuật (P2)',
      'Địa chỉ email tiếp nhận: info@asinu.vn',
      'Website: asinu.vn',
      'Chúng tôi có quyền cập nhật, sửa đổi Chính sách Bảo mật này vào bất kỳ lúc nào để phù hợp với sự thay đổi của công nghệ và quy định pháp luật. Mọi thay đổi lớn sẽ được thông báo trực tiếp đến bạn qua thông báo đẩy trong ứng dụng ít nhất 07 ngày trước khi chính sách mới có hiệu lực.'
    ]
  },
  dataDeletion: {
    title: 'Chính Sách Và Hướng Dẫn Yêu Cầu Xóa Dữ Liệu',
    updated: 'Cập nhật lần cuối: Ngày 22 tháng 05 năm 2026',
    sections: [
      'Tại Asinu, Chúng tôi tôn trọng quyền kiểm soát thông tin cá nhân của bạn. Dịch vụ của chúng tôi cung cấp cho người dùng các tùy chọn rõ ràng, minh bạch để yêu cầu xóa tài khoản và toàn bộ dữ liệu cá nhân liên quan.',
      'Chính sách này hướng dẫn chi tiết cách thức yêu cầu xóa dữ liệu trên hệ thống Asinu nhằm đáp ứng đầy đủ chính sách An toàn Dữ liệu (Data Safety) của Google Play Store và Apple App Store.',
      '1. PHƯƠNG THỨC 1: XÓA TÀI KHOẢN TRỰC TIẾP TRONG ỨNG DỤNG (APP)',
      'Nếu ứng dụng Asinu vẫn đang được cài đặt trên điện thoại của bạn, đây là cách nhanh nhất và an toàn nhất để xóa dữ liệu vì hệ thống sẽ tự động xác thực danh tính qua thiết bị của bạn:',
      '1. Mở ứng dụng Asinu trên điện thoại di động và đăng nhập vào tài khoản của bạn.',
      '2. Truy cập vào mục Cá nhân (hoặc Cài đặt) ở góc dưới bên phải màn hình.',
      '3. Chọn mục Quản lý tài khoản.',
      '4. Nhấn vào dòng chữ Xóa tài khoản vĩnh viễn màu đỏ.',
      '5. Hệ thống sẽ hiển thị một hộp thoại cảnh báo về việc mất dữ liệu. Nhấn Xác nhận xóa.',
      '6. Một mã OTP xác nhận cuối cùng sẽ được gửi đến số điện thoại đăng ký của bạn. Nhập mã OTP để hoàn tất.',
      'Sau khi xác nhận, tài khoản của bạn sẽ lập tức bị đăng xuất và chuyển sang trạng thái chờ xóa.',
      '2. PHƯƠNG THỨC 2: YÊU CẦU XÓA TRỰC TUYẾN (DÀNH CHO NGƯỜI ĐÃ GỠ APP)',
      'Đáp ứng yêu cầu bắt buộc của Google/Apple về việc cho phép yêu cầu xóa dữ liệu trực tuyến trên trang web mà không cần đăng nhập hoặc cài đặt lại app.',
      'Nếu bạn đã gỡ cài đặt ứng dụng Asinu hoặc không thể truy cập vào ứng dụng, bạn có thể gửi yêu cầu xóa tài khoản bằng một trong các cách sau:',
      'Cách A: Gửi yêu cầu qua Email Hỗ trợ',
      'Đại ca và người dùng có thể gửi email yêu cầu trực tiếp về địa chỉ:',
      'Email tiếp nhận: hotro@asinu.vn (hoặc admin@asinu.top)',
      'Tiêu đề email: Yêu cầu xóa dữ liệu tài khoản Asinu – [Số điện thoại đăng ký]',
      'Nội dung email cần cung cấp:',
      '– Họ và tên chủ tài khoản:',
      '– Số điện thoại đăng ký tài khoản (Bắt buộc):',
      '– Lý do muốn xóa tài khoản (Tùy chọn – giúp chúng tôi cải tiến dịch vụ):',
      '– Lưu ý: Bạn phải gửi email này từ địa chỉ email đã được liên kết với tài khoản Asinu của bạn (nếu có).',
      'Cách B: Điền Form Yêu Cầu Trực Tuyến Trên Website',
      'Trang web /data-deletion trên trang chủ asinu.vn sẽ tích hợp sẵn một Form nhập liệu đơn giản gồm: Số điện thoại cần xóa và nút Gửi yêu cầu.',
      '3. QUY TRÌNH XỬ LÝ VÀ XÁC MINH YÊU CẦU',
      'Để tránh các hành vi phá hoại tài khoản (ví dụ: một người cố ý yêu cầu xóa tài khoản của người khác), Chúng tôi áp dụng quy trình xác minh nghiêm ngặt sau:',
      '1. Gửi mã OTP xác thực: Sau khi nhận được yêu cầu qua Email hoặc Form trực tuyến, hệ thống tự động (hoặc nhân viên hỗ trợ của chúng tôi) sẽ gửi một mã OTP SMS hoặc thực hiện một cuộc gọi xác thực đến đúng số điện thoại được yêu cầu xóa.',
      '2. Thời gian chờ (Cool-off Period): Sau khi xác thực thành công, tài khoản sẽ được khóa tạm thời và bước vào thời gian chờ xóa kéo dài 72 giờ làm việc. Trong thời gian này, bạn có thể liên hệ lại với chúng tôi để hủy bỏ yêu cầu xóa tài khoản nếu thay đổi quyết định.',
      '3. Xóa vĩnh viễn: Sau khi kết thúc thời gian chờ 72 giờ, hệ thống sẽ tiến hành xóa dữ liệu vật lý trên máy chủ.',
      '4. CHI TIẾT DỮ LIỆU SẼ BỊ XÓA VÀ DỮ LIỆU GIỮ LẠI',
      'Khi yêu cầu xóa tài khoản của bạn được thực thi thành công, các loại dữ liệu sau đây sẽ chịu tác động:',
      'A. Dữ liệu bị Xóa vĩnh viễn (Hoặc Ẩn danh hóa hoàn toàn)',
      '1. Thông tin định danh: Họ tên, số điện thoại, địa chỉ email, ảnh đại diện, thông tin thiết bị UUID của bạn sẽ bị xóa vĩnh viễn khỏi bảng dữ liệu người dùng.',
      '2. Dữ liệu liên kết gia đình: Mọi mối quan hệ kết nối chia sẻ dữ liệu với tài khoản của người thân hoặc người giám hộ sẽ bị hủy bỏ hoàn toàn.',
      '3. Dữ liệu Sức khỏe (Nhạy cảm): Toàn bộ lịch sử các chỉ số sinh hiệu đo lường (Huyết áp, Nhịp tim, SpO2, Đường huyết) và lịch sử bệnh án, ghi chú y tế sẽ bị xóa sạch khỏi bộ nhớ máy chủ chính.',
      '4. Dữ liệu định vị: Tất cả nhật ký định vị GPS phục vụ tính năng cứu hộ khẩn cấp SOS sẽ bị xóa vĩnh viễn.',
      'B. Dữ liệu được Giữ lại làm ngoại lệ (Bắt buộc theo Luật định)',
      'Theo các quy định pháp luật của Việt Nam (Luật Kế toán, Luật Quản lý Thuế), một số dữ liệu tối thiểu sau không thể xóa ngay lập tức mà phải lưu trữ cách ly để phục vụ mục đích kiểm toán:',
      '1. Lịch sử giao dịch tài chính: Hóa đơn VAT, chứng từ thanh toán nâng cấp gói VIP hoặc giao dịch mua dịch vụ liên kết sẽ được lưu trữ an toàn trong thời hạn tối thiểu từ 5 đến 10 năm theo quy định của Luật Kế toán.',
      '2. Thông tin dữ liệu ẩn danh: Một số chỉ số sức khỏe thô sau khi đã được ẩn danh hóa hoàn toàn (tức là đã bóc tách toàn bộ thông tin định danh, số điện thoại và không còn bất kỳ khả năng nào để liên kết ngược lại với danh tính của bạn) có thể được giữ lại trong tập dữ liệu nghiên cứu nội bộ để tiếp tục huấn luyện AI phát hiện bệnh sớm của Asinu.',
      'Mọi thắc mắc hoặc khó khăn trong quá trình gửi yêu cầu xóa dữ liệu, xin đại ca và các bạn vui lòng liên hệ ngay với chúng tôi qua số điện thoại hỗ trợ kỹ thuật hiển thị trên ứng dụng hoặc qua email hotro@asinu.vn để được hỗ trợ kịp thời.'
    ]
  }
};

const en: LegalContent = {
  terms: {
    title: 'Terms of Service',
    updated: 'Last updated: May 22, 2026',
    sections: [
      'Welcome to the Asinu Health Ecosystem (collectively, “Asinu” or “We”).',
      'Please read these Terms of Service carefully before using the Asinu mobile app or related websites. By creating an account, downloading the app, or using any part of the Service, you agree to be legally bound by these Terms, including our Privacy Policy. If you do not agree, stop using the Service immediately.',
      '1. MEDICAL DISCLAIMER',
      '1. Not a medical institution or diagnostic device:',
      '– Asinu is a technology service that helps connect family members and doctors and records/displays vital signs from external devices such as smartwatches and Bluetooth blood pressure monitors.',
      '– Asinu IS NOT a medical institution. It does not provide emergency medical care, and the content shown in the app (including charts, automated health alerts, and habit suggestions) CANNOT replace professional diagnosis, prescriptions, specialist advice, or a licensed physician’s treatment plan.',
      '2. Do not rely on the system in emergencies:',
      '– Automatic health alerts depend on device accuracy, Bluetooth, carrier networks, and internet connectivity. We do not guarantee 100% timely delivery in every technical condition.',
      '– EMERGENCY: If the user (especially an older adult) has sudden health deterioration or a life-threatening situation, the user or family member MUST immediately contact emergency services at 115 or go to the nearest medical facility. Do not wait for Asinu’s response or delay care based on app readings.',
      '3. Health-related liability disclaimer:',
      '– Asinu disclaims liability for any health, injury, complication, or death resulting from:',
      '– inaccurate readings from peripheral devices;',
      '– internet/network/system failures that delay SOS alerts;',
      '– the user or family changing medication or treatment without a direct specialist instruction based on data from the app;',
      '– advice from partner doctors on the platform (those doctors remain professionally responsible for their telemedicine decisions under applicable medical laws).',
      '2. ACCOUNT REGISTRATION AND SECURITY',
      '1. Eligibility: Users registering for direct health tracking accounts must be 18+ or have direct consent/supervision from a legal guardian (for older adults who cannot independently handle technology or for minors).',
      '2. Registration details: You agree to provide a real phone number and accurate personal information. You are fully responsible under law for the accuracy of that information.',
      '3. Account security: You are responsible for safeguarding your password and device. Any activity through your account is deemed to be performed by you. If you detect unauthorized access, notify Asinu support immediately.',
      '3. PAYMENT AND LOYALTY POINTS (OR VIRTUAL CURRENCY)',
      '1. Paid services: Asinu offers free services and paid upgrades (such as advanced tracking, automated call alerts, and private doctor consultation). Pricing and terms are shown clearly in the app. Payments follow third-party policies (Apple IAP, Google Billing, or local payment gateways).',
      '2. Loyalty points:',
      '– Users may earn Loyalty Points through healthy activities, completing tracking tasks, or purchasing upgrade packages.',
      '– IMPORTANT: Loyalty Points have NO direct cash value and cannot be converted into cash, gold, or equivalent payment instruments outside the app. They may only be used to:',
      '– unlock VIP features in Asinu;',
      '– redeem vouchers for partner clinics/hospitals;',
      '– any unauthorized trading/speculation/transfer of points for financial gain is prohibited and will result in permanent account suspension without notice.',
      '4. INTELLECTUAL PROPERTY',
      'All intellectual property related to the Asinu ecosystem, including source code, UI/UX, logo, the “Asinu” trademark, graphics, expert articles, and all accompanying documentation, is exclusively owned by Asinu management (or legal operator).',
      'You may not copy, modify, distribute, reverse engineer, or use these assets for any other commercial purpose without written consent.',
      '5. PROHIBITED USES',
      'You must not:',
      '1. use the app for purposes that violate Vietnamese law;',
      '2. intentionally send fake alerts or spam the SOS button to disrupt support systems or alarm family/doctors;',
      '3. use fake information to register or impersonate doctors/health experts for gain;',
      '4. attack, spread malware/viruses, or probe security vulnerabilities in the app or VPS servers;',
      '5. post or send obscene, defamatory, or culturally inappropriate content in connection chats;',
      '6. MAXIMUM LIABILITY LIMITATION',
      'To the fullest extent permitted by Vietnamese law:',
      '1. We provide the Service “as is” and make no guarantees of uninterrupted or error-free operation.',
      '2. In all cases, Asinu’s total liability for any claim arising out of or related to the Service will not exceed the amount you actually paid for paid Asinu services in the previous twelve (12) months before the dispute arose.',
      '7. SUSPENSION AND TERMINATION',
      '1. By you: You may stop using the Service and request account deletion at any time via `/data-deletion`.',
      '2. By Asinu: We may suspend or permanently terminate access without liability if you materially breach these Terms or if the Service is fully discontinued due to management strategy or law changes.',
      '8. GOVERNING LAW AND DISPUTE RESOLUTION',
      '1. Governing law: These Terms are governed by the laws of the Socialist Republic of Vietnam.',
      '2. Disputes: Any dispute will first be resolved through good-faith negotiation and mediation. If unresolved within 30 days, it will be submitted to the competent People’s Court in Hanoi (or where the Service operator is headquartered) for final resolution.',
      'Feedback or comments about these Terms may be sent to info@asinu.vn.'
    ]
  },
  privacy: {
    title: 'Privacy Policy',
    updated: 'Last updated: May 22, 2026',
    sections: [
      'Welcome to the Asinu Health Ecosystem (including the Asinu iOS/Android mobile app and asinu.vn / asinu.top website, collectively the “Service” or “We”).',
      'We are committed to respecting your privacy and protecting your personal information. This Privacy Policy is designed to comply with Vietnam’s Decree 13/2023/ND-CP on Personal Data Protection, the 2015 Law on Cyber Information Security, and Apple App Store / Google Play data protection requirements.',
      'This policy explains how we collect, use, store, process, share, and protect your personal data when you use the Service. Please read it carefully before registering or using the Service. By tapping “Agree” or continuing to use the app, you are deemed to have read, understood, and voluntarily agreed to this Policy.',
      '1. TYPES OF PERSONAL DATA WE COLLECT',
      'To provide effective health tracking and family connection features, we collect the following categories of personal data:',
      'A. Basic personal data',
      '1. Identity information: full name, date of birth, gender, profile photo.',
      '2. Contact information: phone number (used as the primary login account and to receive emergency notifications), email address, home address (for emergency support or medical device delivery).',
      '3. Family relationships: links between the elderly account (the person needing care) and the family/guardian account (the monitor).',
      '4. Financial information: transaction history and payment invoices when you upgrade a service package or purchase connected healthcare services (we do not store your detailed card or bank account information; payments are processed securely by licensed payment gateways).',
      'B. Sensitive personal data (Health Data)',
      'Under Vietnamese law, health information is sensitive personal data and requires special protection. We collect:',
      '1. Direct vital signs: blood pressure, heart rate, blood oxygen (SpO2), blood glucose, BMI, height, and weight.',
      '2. Additional medical information: medical history, drug allergies, and daily health notes updated by you or your family.',
      '3. Medical consultation data: consultation notes and recommendations from connected doctors/healthcare experts when you choose to use that service.',
      '4. Location data: GPS location of the device (collected only when you enable the “Send emergency SOS alert” feature to help family or emergency personnel identify the exact location in a dangerous situation).',
      'C. Automatically collected technical data',
      '1. Device information: IP address, device type, operating system, unique device identifier (UUID), and language setting.',
      '2. Activity data (log data): app usage time, features you interacted with, and crash logs for debugging and performance improvements.',
      '2. PURPOSE AND LEGAL BASIS FOR PROCESSING',
      'We process your personal data based on valid legal grounds including your explicit and voluntary consent and the performance of a service contract. Specific purposes include:',
      '1. Service operation: account setup, storing real-time personal health history, and showing charts for easier tracking.',
      '2. Family connection: automatically sharing your health indicators with family/guardian accounts you explicitly connect and authorize in the app.',
      '3. Automatic emergency alerts: detecting unsafe health thresholds (for example, extremely high blood pressure or abnormal heart rate) and sending instant push, SMS, or auto-call alerts to your emergency contacts.',
      '4. Professional healthcare support: sharing health indicator data with doctors or healthcare experts you authorize for online consultations.',
      '5. Algorithm improvement: analyzing anonymized data to improve early risk prediction and user experience.',
      '6. Security and fraud prevention: user identity verification, unauthorized access detection, and system hardening.',
      '3. CONSENT MANAGEMENT',
      '1. Active opt-in: On first install, you are asked to read this policy and check the box saying you agree to the Privacy Policy and allow collection of personal health data. This is mandatory for a health-tracking app.',
      '2. Withdrawing consent: You may withdraw consent at any time by:',
      '– disabling data permissions (Bluetooth, Location, Notifications) in your mobile device settings;',
      '– emailing support to request withdrawal of consent;',
      '– requesting permanent account deletion (all processing then stops and data is deleted under Section 7).',
      'Note: withdrawing consent does not affect the legality of processing conducted before withdrawal.',
      '4. SHARING AND DISCLOSURE OF PERSONAL DATA',
      'We absolutely do NOT sell, rent, or exchange your personal data with any third party for commercial or advertising purposes. Your data is only shared in the following limited cases:',
      '1. Family members and guardians you designate: the system sends health data only to the family accounts you explicitly connect and authorize in the app. You can disconnect at any time.',
      '2. Authorized doctors and medical facilities: when you use remote consultation on Asinu, your health data is shared with the doctor you selected.',
      '3. Technical processors: we work with reputable service providers (such as AWS/Google Cloud, Coolify/Nginx, and Twilio/n8n). They may access only the minimum data necessary to keep the system running and are bound by strict confidentiality obligations.',
      '4. Legal requests: we may provide your personal data to Vietnamese government or law-enforcement authorities when a formal lawful request is made in accordance with applicable procedures.',
      '5. SECURITY AND RETENTION OF SENSITIVE DATA',
      'For health data (sensitive data), we apply the highest technical security standards, including:',
      '1. In-transit encryption: all data transferred between your mobile app and our servers is encrypted using HTTPS/TLS.',
      '2. At-rest encryption: health data and identity data stored in our SQL/PostgreSQL database on our VPS are encrypted using AES-256. Decryption keys are stored separately in a secure key-management system.',
      '3. Access control: Asinu technical staff do not have direct access to your raw unencrypted data. Database access for maintenance is granted only temporarily to the Head of Engineering (P2) upon approval and is recorded in an immutable audit log.',
      '4. Safe backup: data is automatically backed up daily and stored encrypted on a separate backup server to protect against hardware failure.',
      '6. YOUR RIGHTS AND OBLIGATIONS',
      'A. Your rights under Decree 13/2023/ND-CP:',
      '1. Right to know: you may know what personal data processing is taking place.',
      '2. Right to consent or refuse: you may consent or refuse processing.',
      '3. Right to access and correct: you can access your personal page in the app to view and edit your basic personal information at any time.',
      '4. Right to withdraw consent and delete data: you may ask us to permanently delete all of your personal information from our system.',
      '5. Right to restrict or object to processing: you may ask us to stop sharing information with family members or doctors while keeping the account.',
      '6. Right to complain and claim damages: according to law if we violate our security commitments.',
      'B. Your obligations:',
      '1. Provide accurate, genuine personal information and a valid phone number.',
      '2. Keep your account credentials secure. Do not share passwords or devices with others to avoid unintended data leakage.',
      '3. Notify us immediately if you detect any unauthorized access to your account.',
      '7. DATA DELETION REQUEST PROCESS',
      'If you no longer want to use Asinu, you may request account deletion and personal data deletion in two ways:',
      '1. In-app: go to Account Settings -> Delete account permanently. The system will automatically send the request to the server.',
      '2. Online: visit asinu.vn/data-deletion and submit the deletion form without logging in.',
      'Our process:',
      'After receiving the request, we verify account ownership via an OTP sent to the registered phone number.',
      'Within a maximum of 72 working hours after successful verification, all identity data, family information, and health history in the primary database will be permanently deleted (or fully anonymized so it can no longer be linked to your identity).',
      'A minimal set of billing or financial-obligation records may be stored separately as an exception under Vietnamese accounting law and will never be used for any other purpose.',
      '8. DATA CONTROLLER / CONTACT INFORMATION',
      'For questions or requests to exercise your personal data rights, please contact Asinu’s Data Protection team:',
      'Operator: Asinu Health Ecosystem',
      'Data protection leads: Head of Legal (P6) & Head of Engineering (P2)',
      'Contact email: info@asinu.vn',
      'Website: asinu.vn',
      'We may update or revise this Privacy Policy at any time to reflect changes in technology and law. Major changes will be notified to you directly via in-app push notification at least 7 days before the new policy becomes effective.'
    ]
  },
  dataDeletion: {
    title: 'Chính Sách Và Hướng Dẫn Yêu Cầu Xóa Dữ Liệu',
    updated: 'Cập nhật lần cuối: Ngày 22 tháng 05 năm 2026',
    sections: [
      'Tại Asinu, Chúng tôi tôn trọng quyền kiểm soát thông tin cá nhân của bạn. Dịch vụ của chúng tôi cung cấp cho người dùng các tùy chọn rõ ràng, minh bạch để yêu cầu xóa tài khoản và toàn bộ dữ liệu cá nhân liên quan.',
      'Chính sách này hướng dẫn chi tiết cách thức yêu cầu xóa dữ liệu trên hệ thống Asinu nhằm đáp ứng đầy đủ chính sách An toàn Dữ liệu (Data Safety) của Google Play Store và Apple App Store.',
      '1. PHƯƠNG THỨC 1: XÓA TÀI KHOẢN TRỰC TIẾP TRONG ỨNG DỤNG (APP)',
      'Nếu ứng dụng Asinu vẫn đang được cài đặt trên điện thoại của bạn, đây là cách nhanh nhất và an toàn nhất để xóa dữ liệu vì hệ thống sẽ tự động xác thực danh tính qua thiết bị của bạn:',
      '1. Mở ứng dụng Asinu trên điện thoại di động và đăng nhập vào tài khoản của bạn.',
      '2. Truy cập vào mục Cá nhân (hoặc Cài đặt) ở góc dưới bên phải màn hình.',
      '3. Chọn mục Quản lý tài khoản.',
      '4. Nhấn vào dòng chữ Xóa tài khoản vĩnh viễn màu đỏ.',
      '5. Hệ thống sẽ hiển thị một hộp thoại cảnh báo về việc mất dữ liệu. Nhấn Xác nhận xóa.',
      '6. Một mã OTP xác nhận cuối cùng sẽ được gửi đến số điện thoại đăng ký của bạn. Nhập mã OTP để hoàn tất.',
      'Sau khi xác nhận, tài khoản của bạn sẽ lập tức bị đăng xuất và chuyển sang trạng thái chờ xóa.',
      '2. PHƯƠNG THỨC 2: YÊU CẦU XÓA TRỰC TUYẾN (DÀNH CHO NGƯỜI ĐÃ GỠ APP)',
      'Đáp ứng yêu cầu bắt buộc của Google/Apple về việc cho phép yêu cầu xóa dữ liệu trực tuyến trên trang web mà không cần đăng nhập hoặc cài đặt lại app.',
      'Nếu bạn đã gỡ cài đặt ứng dụng Asinu hoặc không thể truy cập vào ứng dụng, bạn có thể gửi yêu cầu xóa tài khoản bằng một trong các cách sau:',
      'Cách A: Gửi yêu cầu qua Email Hỗ trợ',
      'Đại ca và người dùng có thể gửi email yêu cầu trực tiếp về địa chỉ:',
      'Email tiếp nhận: hotro@asinu.vn (hoặc admin@asinu.top)',
      'Tiêu đề email: Yêu cầu xóa dữ liệu tài khoản Asinu – [Số điện thoại đăng ký]',
      'Nội dung email cần cung cấp:',
      '– Họ và tên chủ tài khoản:',
      '– Số điện thoại đăng ký tài khoản (Bắt buộc):',
      '– Lý do muốn xóa tài khoản (Tùy chọn – giúp chúng tôi cải tiến dịch vụ):',
      '– Lưu ý: Bạn phải gửi email này từ địa chỉ email đã được liên kết với tài khoản Asinu của bạn (nếu có).',
      'Cách B: Điền Form Yêu Cầu Trực Tuyến Trên Website',
      'Trang web /data-deletion trên trang chủ asinu.vn sẽ tích hợp sẵn một Form nhập liệu đơn giản gồm: Số điện thoại cần xóa và nút Gửi yêu cầu.',
      '3. QUY TRÌNH XỬ LÝ VÀ XÁC MINH YÊU CẦU',
      'Để tránh các hành vi phá hoại tài khoản (ví dụ: một người cố ý yêu cầu xóa tài khoản của người khác), Chúng tôi áp dụng quy trình xác minh nghiêm ngặt sau:',
      '1. Gửi mã OTP xác thực: Sau khi nhận được yêu cầu qua Email hoặc Form trực tuyến, hệ thống tự động (hoặc nhân viên hỗ trợ của chúng tôi) sẽ gửi một mã OTP SMS hoặc thực hiện một cuộc gọi xác thực đến đúng số điện thoại được yêu cầu xóa.',
      '2. Thời gian chờ (Cool-off Period): Sau khi xác thực thành công, tài khoản sẽ được khóa tạm thời và bước vào thời gian chờ xóa kéo dài 72 giờ làm việc. Trong thời gian này, bạn có thể liên hệ lại với chúng tôi để hủy bỏ yêu cầu xóa tài khoản nếu thay đổi quyết định.',
      '3. Xóa vĩnh viễn: Sau khi kết thúc thời gian chờ 72 giờ, hệ thống sẽ tiến hành xóa dữ liệu vật lý trên máy chủ.',
      '4. CHI TIẾT DỮ LIỆU SẼ BỊ XÓA VÀ DỮ LIỆU GIỮ LẠI',
      'Khi yêu cầu xóa tài khoản của bạn được thực thi thành công, các loại dữ liệu sau đây sẽ chịu tác động:',
      'A. Dữ liệu bị Xóa vĩnh viễn (Hoặc Ẩn danh hóa hoàn toàn)',
      '1. Thông tin định danh: Họ tên, số điện thoại, địa chỉ email, ảnh đại diện, thông tin thiết bị UUID của bạn sẽ bị xóa vĩnh viễn khỏi bảng dữ liệu người dùng.',
      '2. Dữ liệu liên kết gia đình: Mọi mối quan hệ kết nối chia sẻ dữ liệu với tài khoản của người thân hoặc người giám hộ sẽ bị hủy bỏ hoàn toàn.',
      '3. Dữ liệu Sức khỏe (Nhạy cảm): Toàn bộ lịch sử các chỉ số sinh hiệu đo lường (Huyết áp, Nhịp tim, SpO2, Đường huyết) và lịch sử bệnh án, ghi chú y tế sẽ bị xóa sạch khỏi bộ nhớ máy chủ chính.',
      '4. Dữ liệu định vị: Tất cả nhật ký định vị GPS phục vụ tính năng cứu hộ khẩn cấp SOS sẽ bị xóa vĩnh viễn.',
      'B. Dữ liệu được Giữ lại làm ngoại lệ (Bắt buộc theo Luật định)',
      'Theo các quy định pháp luật của Việt Nam (Luật Kế toán, Luật Quản lý Thuế), một số dữ liệu tối thiểu sau không thể xóa ngay lập tức mà phải lưu trữ cách ly để phục vụ mục đích kiểm toán:',
      '1. Lịch sử giao dịch tài chính: Hóa đơn VAT, chứng từ thanh toán nâng cấp gói VIP hoặc giao dịch mua dịch vụ liên kết sẽ được lưu trữ an toàn trong thời hạn tối thiểu từ 5 đến 10 năm theo quy định của Luật Kế toán.',
      '2. Thông tin dữ liệu ẩn danh: Một số chỉ số sức khỏe thô sau khi đã được ẩn danh hóa hoàn toàn (tức là đã bóc tách toàn bộ thông tin định danh, số điện thoại và không còn bất kỳ khả năng nào để liên kết ngược lại với danh tính của bạn) có thể được giữ lại trong tập dữ liệu nghiên cứu nội bộ để tiếp tục huấn luyện AI phát hiện bệnh sớm của Asinu.',
      'Mọi thắc mắc hoặc khó khăn trong quá trình gửi yêu cầu xóa dữ liệu, xin đại ca và các bạn vui lòng liên hệ ngay với chúng tôi qua số điện thoại hỗ trợ kỹ thuật hiển thị trên ứng dụng hoặc qua email hotro@asinu.vn để được hỗ trợ kịp thời.'
    ]
  }
};

export const getLegalText = (lang: 'vi' | 'en' = 'vi'): LegalContent => {
  return lang === 'en' ? en : vi;
};

/** @deprecated Use getLegalText() instead for language-reactive content */
export const LEGAL_TEXT = getLegalText('vi');
